### ISSUE TITLE
Add few examples how to use it

### ISSUE THREAD

**Issue by trajakovic** [sbueringer/kustomize-webhook#1]
Examples and maybe some usecases would be very benefitial. Thank you

**Comment by sbueringer** [comment]
Have you seen the example here: https://github.com/sbueringer/kustomize-webhook/blob/master/deploy/webhook.yaml ?

P.S.: I'm not sure how advisable it is to depend on this repository. I probably won't really maintain it, I just use it for my purposes

**Comment by trajakovic** [comment]
@sbueringer ok, too bad, project looks promising :)
